id: d0ddffface1946f093464d5cfbe41989
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_131-The_Absorption_of_the_Thus-Gone_One%E2%80%99s_Wisdom_Seal-v1
  language: en
  author: ''
  volume: {}
